name: ROS2 build/tests
on:
  pull_request:
jobs:
  build_and_tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ros_distribution:
          - humble
          - jazzy
        include:
          # https://dlu.github.io/ros_clock/index.html
          - docker_image: ubuntu:jammy
            ros_distribution: humble
          - docker_image: ubuntu:noble
            ros_distribution: jazzy
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build multirobot_map_merge and explore_lite
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: multirobot_map_merge explore_lite
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
      - name: Run gtests manually multirobot_map_merge
        run: |
          . /opt/ros/${{ matrix.ros_distribution }}/setup.sh && . ros_ws/install/setup.sh
          cd ros_ws/build/multirobot_map_merge
          ./test_merging_pipeline
      - name: Run gtests manually explore_lite
        run: |
          . /opt/ros/${{ matrix.ros_distribution }}/setup.sh && . ros_ws/install/setup.sh
          cd ros_ws/build/explore_lite
          ./test_explore
